version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py createsuperuser --no-input && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: silencio_system
    volumes:
      - .:/silencio_system
    ports:
      - "8000:8000"